[package]
name = "finchers-core"
version = "0.11.0-pre"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
mime = "0.3"
http = "0.1"
futures = "0.1"
bytes = "0.4"
scoped-tls = "0.1.1"
either = "1.5.0"
hyper = { version = "0.11.24", default-features = false, optional = true }

[features]
default = ["from_hyper"]
from_hyper = ["hyper"]
