[package]
name = "finchers"
version = "0.12.0-dev" # don't forget to update html_root_url in lib.rs
description = "A combinator library for builidng asynchronous HTTP services"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://finchers-rs.github.io/"
repository = "https://github.com/finchers-rs/finchers.git"
documentation = "https://docs.rs/finchers"
keywords = ["finchers", "web", "framework", "server"]
categories = ["web-programming::http-server"]

include = [
  "Cargo.toml",
  "src/**/*",
  "tests/**/*",
]

[badges]
travis-ci = { repository = "finchers-rs/finchers" }
coveralls = { repository = "finchers-rs/finchers" }
maintenance = { status = "actively-developed" }

[workspace]
members = [
  # "finchers-derive",

  # "examples/basic-auth",
  # "examples/form",
  "examples/todo",
]

[dependencies]
# finchers-derive = { version = "0.12.0-dev", path = "finchers-derive" }

bytes = "0.4.9"
failure = "0.1.2"
futures = "0.1.23"
http = "0.1.10"
hyper = "0.12.7"
log = "0.4.3"
mime = "0.3.8"
percent-encoding = "1.0.1"
pin-utils = "0.1.0-alpha.1"
serde = { version = "1.0.71", features = ["derive"] }
serde_json = "1.0.24"
serde_qs = "0.4.1"
structopt = "0.2.10"
tokio = "0.1.7"

futures-core-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", branch = "master" }
futures-util-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", branch = "master", features = ["tokio-compat"] }
#futures-core-preview = { version = "0.3.0-alpha.3" }
#futures-util-preview = { version = "0.3.0-alpha.3", features = ["tokio-compat"] }

[features]
strict = []
