cargo-features = ["edition"]

[package]
name = "example-todos"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "todos"
path = "src/main.rs"
doc = false

[dependencies]
finchers = { path = "../.." }
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", branch = "master" }
serde = { version = "1.0", features = ["derive"] }
failure = "0.1"
http = "0.1.10"
