[book]
title = "Finchers Users Guide"
description = "The user guide of Finchers"
authors = ["Yusuke Sasaki"]
multilingual = false
src = "src"

[build]
build-dir = "../target/doc/guide"
create-missing = false
