[package]
name = "example-staticfiles"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "staticfiles"
path = "src/main.rs"
doc = false

[dependencies]
finchers = { path = "../.." }
